### ISSUE TITLE
UserStory1 Criar paineis de cadastramento

### ISSUE THREAD

**Issue by danrleypereira** [danrleywillyan/OO#5]
# Development
- [ ] **Painel#1**: Nome(JText e JLabel).
- [ ] **Painel#2**: País(JText e JLbabel).
- [ ] **Painel#3**: Opinião().
- [ ] **Painel#4**: Número de atletas(Jtext e JLabel).
